/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as DmaRouteImport } from './routes/dma'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GasIndexRouteImport } from './routes/gas/index'
import { Route as ElectricIndexRouteImport } from './routes/electric/index'
import { Route as GasSimulatorRouteImport } from './routes/gas/simulator'
import { Route as GasQualityRouteImport } from './routes/gas/quality'
import { Route as GasGovernanceRouteImport } from './routes/gas/governance'
import { Route as GasDmaRouteImport } from './routes/gas/dma'
import { Route as GasAssistantRouteImport } from './routes/gas/assistant'
import { Route as GasAssetsRouteImport } from './routes/gas/assets'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const DmaRoute = DmaRouteImport.update({
  id: '/dma',
  path: '/dma',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GasIndexRoute = GasIndexRouteImport.update({
  id: '/gas/',
  path: '/gas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricIndexRoute = ElectricIndexRouteImport.update({
  id: '/electric/',
  path: '/electric/',
  getParentRoute: () => rootRouteImport,
} as any)
const GasSimulatorRoute = GasSimulatorRouteImport.update({
  id: '/gas/simulator',
  path: '/gas/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const GasQualityRoute = GasQualityRouteImport.update({
  id: '/gas/quality',
  path: '/gas/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const GasGovernanceRoute = GasGovernanceRouteImport.update({
  id: '/gas/governance',
  path: '/gas/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const GasDmaRoute = GasDmaRouteImport.update({
  id: '/gas/dma',
  path: '/gas/dma',
  getParentRoute: () => rootRouteImport,
} as any)
const GasAssistantRoute = GasAssistantRouteImport.update({
  id: '/gas/assistant',
  path: '/gas/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const GasAssetsRoute = GasAssetsRouteImport.update({
  id: '/gas/assets',
  path: '/gas/assets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/dma': typeof DmaRoute
  '/executive': typeof ExecutiveRoute
  '/governance': typeof GovernanceRoute
  '/quality': typeof QualityRoute
  '/simulator': typeof SimulatorRoute
  '/gas/assets': typeof GasAssetsRoute
  '/gas/assistant': typeof GasAssistantRoute
  '/gas/dma': typeof GasDmaRoute
  '/gas/governance': typeof GasGovernanceRoute
  '/gas/quality': typeof GasQualityRoute
  '/gas/simulator': typeof GasSimulatorRoute
  '/electric/': typeof ElectricIndexRoute
  '/gas/': typeof GasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/dma': typeof DmaRoute
  '/executive': typeof ExecutiveRoute
  '/governance': typeof GovernanceRoute
  '/quality': typeof QualityRoute
  '/simulator': typeof SimulatorRoute
  '/gas/assets': typeof GasAssetsRoute
  '/gas/assistant': typeof GasAssistantRoute
  '/gas/dma': typeof GasDmaRoute
  '/gas/governance': typeof GasGovernanceRoute
  '/gas/quality': typeof GasQualityRoute
  '/gas/simulator': typeof GasSimulatorRoute
  '/electric': typeof ElectricIndexRoute
  '/gas': typeof GasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/dma': typeof DmaRoute
  '/executive': typeof ExecutiveRoute
  '/governance': typeof GovernanceRoute
  '/quality': typeof QualityRoute
  '/simulator': typeof SimulatorRoute
  '/gas/assets': typeof GasAssetsRoute
  '/gas/assistant': typeof GasAssistantRoute
  '/gas/dma': typeof GasDmaRoute
  '/gas/governance': typeof GasGovernanceRoute
  '/gas/quality': typeof GasQualityRoute
  '/gas/simulator': typeof GasSimulatorRoute
  '/electric/': typeof ElectricIndexRoute
  '/gas/': typeof GasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/assistant'
    | '/dma'
    | '/executive'
    | '/governance'
    | '/quality'
    | '/simulator'
    | '/gas/assets'
    | '/gas/assistant'
    | '/gas/dma'
    | '/gas/governance'
    | '/gas/quality'
    | '/gas/simulator'
    | '/electric/'
    | '/gas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/assistant'
    | '/dma'
    | '/executive'
    | '/governance'
    | '/quality'
    | '/simulator'
    | '/gas/assets'
    | '/gas/assistant'
    | '/gas/dma'
    | '/gas/governance'
    | '/gas/quality'
    | '/gas/simulator'
    | '/electric'
    | '/gas'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/assistant'
    | '/dma'
    | '/executive'
    | '/governance'
    | '/quality'
    | '/simulator'
    | '/gas/assets'
    | '/gas/assistant'
    | '/gas/dma'
    | '/gas/governance'
    | '/gas/quality'
    | '/gas/simulator'
    | '/electric/'
    | '/gas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AssistantRoute: typeof AssistantRoute
  DmaRoute: typeof DmaRoute
  ExecutiveRoute: typeof ExecutiveRoute
  GovernanceRoute: typeof GovernanceRoute
  QualityRoute: typeof QualityRoute
  SimulatorRoute: typeof SimulatorRoute
  GasAssetsRoute: typeof GasAssetsRoute
  GasAssistantRoute: typeof GasAssistantRoute
  GasDmaRoute: typeof GasDmaRoute
  GasGovernanceRoute: typeof GasGovernanceRoute
  GasQualityRoute: typeof GasQualityRoute
  GasSimulatorRoute: typeof GasSimulatorRoute
  ElectricIndexRoute: typeof ElectricIndexRoute
  GasIndexRoute: typeof GasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dma': {
      id: '/dma'
      path: '/dma'
      fullPath: '/dma'
      preLoaderRoute: typeof DmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/': {
      id: '/gas/'
      path: '/gas'
      fullPath: '/gas/'
      preLoaderRoute: typeof GasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electric/': {
      id: '/electric/'
      path: '/electric'
      fullPath: '/electric/'
      preLoaderRoute: typeof ElectricIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/simulator': {
      id: '/gas/simulator'
      path: '/gas/simulator'
      fullPath: '/gas/simulator'
      preLoaderRoute: typeof GasSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/quality': {
      id: '/gas/quality'
      path: '/gas/quality'
      fullPath: '/gas/quality'
      preLoaderRoute: typeof GasQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/governance': {
      id: '/gas/governance'
      path: '/gas/governance'
      fullPath: '/gas/governance'
      preLoaderRoute: typeof GasGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/dma': {
      id: '/gas/dma'
      path: '/gas/dma'
      fullPath: '/gas/dma'
      preLoaderRoute: typeof GasDmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/assistant': {
      id: '/gas/assistant'
      path: '/gas/assistant'
      fullPath: '/gas/assistant'
      preLoaderRoute: typeof GasAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas/assets': {
      id: '/gas/assets'
      path: '/gas/assets'
      fullPath: '/gas/assets'
      preLoaderRoute: typeof GasAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AssistantRoute: AssistantRoute,
  DmaRoute: DmaRoute,
  ExecutiveRoute: ExecutiveRoute,
  GovernanceRoute: GovernanceRoute,
  QualityRoute: QualityRoute,
  SimulatorRoute: SimulatorRoute,
  GasAssetsRoute: GasAssetsRoute,
  GasAssistantRoute: GasAssistantRoute,
  GasDmaRoute: GasDmaRoute,
  GasGovernanceRoute: GasGovernanceRoute,
  GasQualityRoute: GasQualityRoute,
  GasSimulatorRoute: GasSimulatorRoute,
  ElectricIndexRoute: ElectricIndexRoute,
  GasIndexRoute: GasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
